[package]
name = "MessageBoard"
version = "1.0.0"
authors = []

[addresses]
message_board_addr = "0x662ff6b8d3ec62342ebe595b0ca2c4954a696156f4ec914ce2ff4bd09d82cc34"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
